# Generated by Django 5.2 on 2025-05-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_district_emd_name_district_emd_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="district",
            name="city_no",
        ),
        migrations.AlterField(
            model_name="district",
            name="city_name",
            field=models.CharField(db_index=True, max_length=40, verbose_name="시 이름"),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_name",
            field=models.CharField(db_index=True, max_length=40, verbose_name="구 이름"),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_no",
            field=models.CharField(db_index=True, max_length=10, verbose_name="구 고유번호"),
        ),
        migrations.AlterField(
            model_name="district",
            name="emd_name",
            field=models.CharField(db_index=True, max_length=40, verbose_name="읍면동 이름"),
        ),
        migrations.AlterField(
            model_name="district",
            name="emd_no",
            field=models.CharField(
                db_index=True,
                max_length=10,
                unique=True,
                verbose_name="읍면동 고유번호",
            ),
        ),
    ]
