# Generated by Django 5.2 on 2025-05-08 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "search",
            "0004_remove_district_city_no_alter_district_city_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="city_no",
            field=models.CharField(
                db_index=True,
                max_length=10,
                verbose_name="시 고유번호",
            ),
            preserve_default=False,
        ),
    ]
