# Generated by Django 5.2 on 2025-05-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_district_city_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="city_no",
            field=models.CharField(db_index=True, max_length=20, verbose_name="시 고유번호"),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_no",
            field=models.CharField(db_index=True, max_length=20, verbose_name="구 고유번호"),
        ),
        migrations.AlterField(
            model_name="district",
            name="emd_no",
            field=models.CharField(
                db_index=True,
                max_length=20,
                unique=True,
                verbose_name="읍면동 고유번호",
            ),
        ),
    ]
