# Generated by Django 5.2 on 2025-05-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_posting",
            "0003_jobposting_town_alter_jobposting_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="work_experience",
            field=models.CharField(default="경력, 경력무관", max_length=10),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="employment_type",
            field=models.CharField(default="정규직, 비정규직", max_length=10),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="posting_type",
            field=models.CharField(default="기업,공공", max_length=10),
        ),
    ]
