# Generated by Django 5.2 on 2025-05-02 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_posting",
            "0003_jobposting_town_alter_jobposting_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=5179, verbose_name="근무지 좌표"),
        ),
    ]
