# Generated by Django 5.2 on 2025-05-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_posting", "0004_alter_jobposting_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="city",
            field=models.CharField(db_index=True, default="시,도", max_length=10),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="district",
            field=models.CharField(db_index=True, default="시,군,구", max_length=10),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="town",
            field=models.CharField(db_index=True, default="읍,면,동", max_length=10),
        ),
    ]
