# Generated by Django 5.2 on 2025-05-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_posting", "0004_jobposting_work_experience_and_more"),
        (
            "job_posting",
            "0005_alter_jobposting_city_alter_jobposting_district_and_more",
        ),
    ]

    operations = []
